/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alich
 */
public class Fenêtre extends javax.swing.JFrame {

    ArrayList<Véhicule> Véhicules;
    DefaultListModel modèleListe;
    File fichier;
    FileWriter fw;
    PrintWriter pw;
    /**
     * Creates new form Fenêtre
     */
    public Fenêtre() {
        initComponents();
        Véhicules = new ArrayList<>();
        modèleListe = new DefaultListModel();
        fichier = new File("fichier.veh");
        try {
            fichier = new File("fichier.veh");
            fw = new FileWriter(fichier);
            pw = new PrintWriter(fw);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeVéhicules = new javax.swing.JList<>();
        btnSupprimer = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listeVéhicules);

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnAjouter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnEnregistrer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnFermer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSupprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFermer, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
       int choix = JOptionPane.showConfirmDialog(this, "Etes-vous sur de vouloir sortir?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(choix==0)
        System.exit(0);
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        Véhicule véhicule=null;
        
        String marque,modèle,immatriculation,type;
        int nombrePortes,vitesseMax,choix=0;
        boolean remorque;
        type = JOptionPane.showInputDialog(this, "Entrez le type du Véhicule Voiture/Camion/Moto", 
                "Type", JOptionPane.PLAIN_MESSAGE);
        
        if(type==null){
        
        }
        
        else if(type.equalsIgnoreCase("Voiture")){
            marque = JOptionPane.showInputDialog(this, "Entrez la marque du Véhicule", 
                "Marque", JOptionPane.PLAIN_MESSAGE);
            modèle = JOptionPane.showInputDialog(this, "Entrez le modèle du Véhicule", 
                "Modèle", JOptionPane.PLAIN_MESSAGE);
            immatriculation = JOptionPane.showInputDialog(this, "Entrez l'immatriculation du Véhicule", 
                "Immatriculation", JOptionPane.PLAIN_MESSAGE);
            nombrePortes = Integer.parseInt(JOptionPane.showInputDialog(this, "Entrez le nombre de portes", 
                "Nombre de portes", JOptionPane.PLAIN_MESSAGE));
            véhicule = new Voiture(marque,modèle,immatriculation,nombrePortes);  
        }
            
        else if(type.equalsIgnoreCase("Moto")){
            marque = JOptionPane.showInputDialog(this, "Entrez la marque du Véhicule", 
                "Marque", JOptionPane.PLAIN_MESSAGE);
            modèle = JOptionPane.showInputDialog(this, "Entrez le modèle du Véhicule", 
                "Modèle", JOptionPane.PLAIN_MESSAGE);
            immatriculation = JOptionPane.showInputDialog(this, "Entrez l'immatriculation du Véhicule", 
                "Immatriculation", JOptionPane.PLAIN_MESSAGE);
            vitesseMax = Integer.parseInt(JOptionPane.showInputDialog(this, "Entrez la vitesse maximale", 
                "Vitesse", JOptionPane.PLAIN_MESSAGE));
            véhicule = new Moto(marque, modèle, immatriculation, vitesseMax);
        }
            
        else if(type.equalsIgnoreCase("Camion")){
            marque = JOptionPane.showInputDialog(this, "Entrez la marque du Véhicule", 
                "Marque", JOptionPane.PLAIN_MESSAGE);
            modèle = JOptionPane.showInputDialog(this, "Entrez le modèle du Véhicule", 
                "Modèle", JOptionPane.PLAIN_MESSAGE);
            immatriculation = JOptionPane.showInputDialog(this, "Entrez l'immatriculation du Véhicule", 
                "Immatriculation", JOptionPane.PLAIN_MESSAGE);
            choix = JOptionPane.showConfirmDialog(this,"Le camion a-t-il un remorque?","Remorque",JOptionPane.YES_NO_OPTION);
        if(choix==0)remorque=true;
        else remorque=false;
        véhicule = new Camion(marque, modèle, immatriculation, remorque);
        
        }
        else{
            JOptionPane.showConfirmDialog(this, "Votre choix est incorrect", "choix incorrect", JOptionPane.OK_OPTION);
        }
           Véhicules.add(véhicule);
        modèleListe.add(modèleListe.getSize(), véhicule);
        listeVéhicules.setModel(modèleListe);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        for(Véhicule v:Véhicules){
            pw.println(v);
        }
        pw.close();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
       if(listeVéhicules.isSelectionEmpty())
           JOptionPane.showConfirmDialog(this, "Séléctionner un véhiclue à supprimer",
                   "Pas de séléction", JOptionPane.ERROR_MESSAGE);
       else{
       int indice = listeVéhicules.getSelectedIndex();
               modèleListe.remove(indice);
               Véhicules.remove(indice);
               }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        String marque,modèle,immatriculation;
        int nombrePortes,remorque,vitesseMax;
         if(listeVéhicules.isSelectionEmpty())
           JOptionPane.showConfirmDialog(this, "Séléctionner un véhiclue à modifier",
                   "Pas de séléction", JOptionPane.ERROR_MESSAGE);
         else{
             int indice = listeVéhicules.getSelectedIndex();
             Véhicule v = Véhicules.get(indice);
             marque = JOptionPane.showInputDialog(this, "Changez la marque",
                     v.getMarque());
             v.setMarque(marque);
             modèle = JOptionPane.showInputDialog(this, "Changez le modèle",
                     v.getModèle());
             v.setModèle(modèle);
             immatriculation = JOptionPane.showInputDialog(this, "Changez l'immatriculation",
                     v.getImmatriculation());
             v.setImmatriculation(immatriculation);
             if(v instanceof Voiture){
                 nombrePortes = Integer.valueOf(JOptionPane.showInputDialog(this, "Changez le nombre de portes", ((Voiture) v).getNombrePortes()));
                 ((Voiture) v).setNombrePortes(nombrePortes);
             }
             else if(v instanceof Camion){
                 remorque = JOptionPane.showConfirmDialog(this, "le camion a-t-il un remorque?", "Remorque", JOptionPane.YES_NO_OPTION);
                 boolean choix = true;
                 if(remorque==JOptionPane.NO_OPTION)
                     choix=false;
                 ((Camion) v).setRemorque(choix);
             }
             else if(v instanceof Moto){
                  vitesseMax = Integer.valueOf(JOptionPane.showInputDialog(this, "Changez la vitesse maximale",
                          ((Moto) v).getVitesseMax()));
                  ((Moto) v).setVitesseMax(vitesseMax);
             }
             else{
                 JOptionPane.showMessageDialog(this, "Erreur Inconnue", "Erreur", JOptionPane.ERROR_MESSAGE);
             }
             listeVéhicules.setModel(modèleListe);
         }
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              Fenêtre f = new Fenêtre();
              f.setVisible(true);
              f.setTitle("La Gestion d'un Parking");
              f.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listeVéhicules;
    // End of variables declaration//GEN-END:variables
}
